version: '3.9'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
